[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana = "3CkB1YhoBxHG9uZXJ3fDkjshjb9nXdFQkLSKKNYz9vX7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deployer.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
