[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana = "BwzroF85PpoMMjmvYBgvdtXRggJUNUs6sfw6LydFjTEj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./swap.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
